

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  
  # via 127.0.0.1 to disable public access
  config.vm.network "forwarded_port", guest: 3389, host: 3389, host_ip: "127.0.0.1"
  # config.vm.network "forwarded_port", guest: 3389, host: 3389

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"
  

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    # vb.gui = true
    vb.memory = "4096"
    vb.cpus = "2"
    vb.customize ["modifyvm", :id, "--vram", "256"]
  end
  
  config.vm.provision "shell", path: "script.sh"
  config.vm.provision "file", source: "config", destination: "~/.config/i3/config"

  
  config.vm.provision "shell" do |s|
    s.privileged = true
    s.inline = "echo reboot is happening"
    s.reboot = true
  end

end
