
# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  # config.vm.box = "ubuntu/focal64"
  config.vm.box = "generic/alpine314"

  
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"


  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = true
    vb.memory = "2048"
    vp.cpus = "2"
    vb.customize ["modifyvm", :id, "--vram", "256"]
  end
  
  config.vm.provision "shell", inline: <<-SCRIPT
  apk update 
  DEBIAN_FRONTEND=noninteractive apk upgrade

  # GUI 
  # DEBIAN_FRONTEND=noninteractive apt-get install -y xfce4 virtualbox-guest-dkms virtualbox-guest-utils virtualbox-guest-x11
  DEBIAN_FRONTEND=noninteractive apk add xfce4 xfce4-terminal xfce4-screensaver lightdm-gtk-greeter 

  # VBox dodatki
  # VBoxClient --clipboard
  # VBoxClient --draganddrop
  # VBoxClient --vmsvga
  # VBoxClient --checkhostversion
  # VBoxClient --seamless
  

  # GNS3 z vgrajenim wiresharkom
  # add-apt-repository ppa:gns3/ppa -y
  DEBIAN_FRONTEND=noninteractive apk add gns3-gui --repository https://github.com/GNS3/gns3-gui
  DEBIAN_FRONTEND=noninteractive apk add gns3-server --repository https://pkgs.alpinelinux.org/package/v3.10/community/x86_64/gns3-server
  
  rc-service dbus start
  rc-update add dbus
  rc-service lightdm start
  rc-update add lightdm

  SCRIPT
  
  
  config.vm.provision "shell" do |s|
    s.privileged = true
    s.inline = "echo reboot is happening"
    s.reboot = true
  end

  # config.vm.provision "shell", inline: "service lightdm start"

end
